name = "SparseColumnPivotedQR"
uuid = "a57abbd0-fea5-4d57-96be-5e525945e8e4"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com> and contributors"]
version = "2.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"

[extensions]
SparseColumnPivotedQRAMDExt = "AMD"

[compat]
AMD = "0.5"
ForwardDiff = "0.10, 1"
LinearAlgebra = "1"
PrecompileTools = "1"
Random = "1"
SafeTestsets = "0.1, 1"
SciMLTesting = "1"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLTesting = "09d9d899-5365-40a9-917a-5f67fddea283"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AMD", "ForwardDiff", "Random", "SafeTestsets", "SciMLTesting", "Test"]
